# Generated by Django 5.0.7 on 2025-01-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('track_id', models.IntegerField()),
                ('class_name', models.CharField(max_length=255)),
                ('speed', models.FloatField()),
                ('numberplate', models.TextField()),
            ],
        ),
    ]
